#!/bin/bash
tmux send-keys -t 0 C-d
tmux send-keys -t 1 C-d
tmux send-keys -t 2 C-d
tmux send-keys -t 3 C-d
tmux send-keys -t 4 C-d
tmux send-keys -t 5 C-d
tmux send-keys -t 6 C-d
tmux send-keys -t 7 C-d
tmux send-keys -t 8 C-d
tmux send-keys -t 9 C-d



