#!/bin/env ruby

if ARGV.empty?
  puts "usage: setup_mux [app_name]"
  exit 1
end

app_name = ARGV[0]
ENV['app_name'] = app_name

unless File.exist?(ENV['HOME'] + "/.tmuxinator/#{app_name}.yml")
  `erb ~/rc_files/tmuxinator_sample.yml > ~/.tmuxinator/#{app_name}.yml`
end

puts "create ~/.tmuxinator/#{app_name}.yml"



