#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/googutil'

files = read_files_with_lines(ARGV)[0...10]
Dir.chdir read_pwd
exec('vim ' +  files.map{|f| %Q("+e #{ f[1].to_i > 0 ? "+#{f[1]}" : ''} #{File.expand_path(f[0])}")}.join(' '))

